// Downloads real product front photos from Open Food Facts (ODbL / CC BY-SA) into public/snacks.
import fs from "node:fs";
const Q = {
  coke: "coca-cola classic can", "diet-coke": "diet coke can", "canada-dry": "canada dry ginger ale", "fuze-tea": "fuze iced tea lemon",
  "lacroix-lime": "lacroix lime", "lacroix-pamp": "lacroix pamplemousse", "cold-brew": "la colombe cold brew", kombucha: "gt's synergy gingerade",
  "yerba-mate": "guayaki yerba mate", celsius: "celsius sparkling orange", "chobani-plain": "chobani plain greek yogurt", "chobani-straw": "chobani strawberry greek yogurt",
  "sabra-hummus": "sabra classic hummus", babybel: "mini babybel original", "string-cheese": "sargento string cheese", carrots: "bolthouse baby carrots",
  lays: "lay's classic potato chips", kettle: "kettle brand sea salt chips", cheetos: "flamin hot cheetos", skinnypop: "skinnypop original popcorn",
  pretzels: "snyder's mini pretzels", "kale-chips": "rhythm kale chips", "gin-gins": "gin gins ginger chews", prunes: "sunsweet pitted prunes",
  "marys-crackers": "mary's gone crackers original", quest: "quest protein bar", "nature-valley": "nature valley oats n honey", kind: "kind dark chocolate nuts sea salt",
  larabar: "larabar cashew cookie", jerky: "jack link's beef jerky original", almonds: "blue diamond almonds", "trail-mix": "planters trail mix",
  seaweed: "gimme seaweed sea salt", snickers: "snickers bar", haribo: "haribo goldbears", kcups: "green mountain coffee k-cup",
  oatly: "oatly barista edition", twinings: "twinings green tea", magnum: "magnum classic ice cream", outshine: "outshine mango fruit bars",
  sprite: "sprite lemon lime can", "red-bull": "red bull energy drink 250ml", gatorade: "gatorade cool blue", doritos: "doritos nacho cheese",
  "sun-chips": "sunchips harvest cheddar", goldfish: "goldfish cheddar crackers", "cheez-it": "cheez-it original", pringles: "pringles original",
  oreo: "oreo original cookies", belvita: "belvita blueberry", clif: "clif bar chocolate chip", rxbar: "rxbar chocolate sea salt",
  "rice-krispies": "rice krispies treats", mms: "m&m's peanut", twix: "twix", "sour-patch": "sour patch kids", welchs: "welch's fruit snacks mixed fruit",
};
const ok = [];
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
for (const [id, q] of Object.entries(Q)) {
  if (fs.existsSync(`public/snacks/${id}.jpg`)) continue;
  await sleep(3500); // OFF rate limit
  try {
    const url = `https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&json=1&page_size=8&fields=product_name,image_front_url`;
    const r = await fetch(url, { headers: { "user-agent": "SnackOverflowHackathon/0.1" } }).then((x) => x.json());
    const hit = r.products?.find((p) => p.image_front_url);
    if (!hit) { console.log("MISS", id); continue; }
    const img = await fetch(hit.image_front_url).then((x) => x.arrayBuffer());
    fs.writeFileSync(`public/snacks/${id}.jpg`, Buffer.from(img));
    ok.push(id); console.log("OK  ", id, "<-", hit.product_name);
  } catch (e) { console.log("ERR ", id, e.message); }
}
const all = fs.readdirSync("public/snacks").filter((f) => f.endsWith(".jpg")).map((f) => f.replace(".jpg", ""));
fs.writeFileSync("lib/images.ts", `// generated by scripts/fetch-images.mjs\nexport const IMAGES = new Set<string>(${JSON.stringify(all)});\n`);
